### ISSUE TITLE
Build fails in MacOS with error: use of undeclared identifier 'CLOCK_REALTIME'

### ISSUE THREAD

**Issue by danimtb** [eclipse-paho/paho.mqtt.c#546]
Building Paho C 1.3.0 in MacOS osx10.11 and xcode7.3-1480691248 fails with `error: use of undeclared identifier 'CLOCK_REALTIME'`. In Other versions of OSX paho.mqtt.c is building fine.

Tested with the following configuration:

Settings and options:
```
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.version=7.3
[options]
paho-c:shared=True
```

CMake build definitions:
```
"PAHO_BUILD_DOCUMENTATION" = OFF
"PAHO_BUILD_SAMPLES" = OFF
"PAHO_BUILD_DEB_PACKAGE" = OFF
"PAHO_BUILD_STATIC" = OFF
"PAHO_WITH_SSL"] = OFF
```

Build trace:
```
[  7%] Building C object src/CMakeFiles/common_obj.dir/MQTTProtocolClient.c.o
[  7%] Building C object src/CMakeFiles/common_obj.dir/Clients.c.o
[ 10%] Building C object src/CMakeFiles/common_obj.dir/utf-8.c.o
[ 14%] Building C object src/CMakeFiles/common_obj.dir/StackTrace.c.o
[ 17%] Building C object src/CMakeFiles/common_obj.dir/MQTTPacket.c.o
[ 21%] Building C object src/CMakeFiles/common_obj.dir/MQTTPacketOut.c.o
[ 25%] Building C object src/CMakeFiles/common_obj.dir/Messages.c.o
[ 28%] Building C object src/CMakeFiles/common_obj.dir/Tree.c.o
[ 32%] Building C object src/CMakeFiles/common_obj.dir/Socket.c.o
[ 35%] Building C object src/CMakeFiles/common_obj.dir/Log.c.o
[ 39%] Building C object src/CMakeFiles/common_obj.dir/MQTTPersistence.c.o
[ 42%] Building C object src/CMakeFiles/common_obj.dir/Thread.c.o
/Users/travis/.conan/data/paho-c/1.3.0/conan/testing/build/b52bdce8baa4990d8fab21d7219c39b9bda1a211/sources/src/Thread.c:412:2: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
        clock_gettime(CLOCK_REALTIME, &cond_timeout);
        ^
/Users/travis/.conan/data/paho-c/1.3.0/conan/testing/build/b52bdce8baa4990d8fab21d7219c39b9bda1a211/sources/src/Thread.c:412:16: error: use of undeclared identifier 'CLOCK_REALTIME'
        clock_gettime(CLOCK_REALTIME, &cond_timeout);
                      ^
1 warning and 1 error generated.
make[2]: *** [src/CMakeFiles/common_obj.dir/Thread.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/common_obj.dir/all] Error 2
make: *** [all] Error 2
```

Travis Log:
https://travis-ci.org/conan-community/conan-paho-c/jobs/430953948

Possible cause could be that CLOCK_REALTIME is not defined in osx10.11 as this comment points out https://github.com/pjreddie/darknet/pull/62

Hope the information is enough to solve the issue. Thanks!

**Comment by icraggs** [comment]
Used to use gettimeofday() but changed it when planning to use CLOCK_MONOTONIC instead of CLOCK_REALTIME.  

I guess one question is how old a version of OS/X is to be supported at any point.  Probably should revert to gettimeofday() then, for those cases where CLOCK_MONOTONIC is not available or going to be used.

**Comment by danimtb** [comment]
Is there any documentation regarding the platforms supported?

I wouldn't mind dropping osx10.11 support, just opened the issue to make the maintainers of the library aware that this was working in version 1.2.0 and is broken after 1.3.0 release.

**Comment by windbender** [comment]
I'd be fine with dropping. version <= 10.11.  on OS X,  then raise a specific issue around recoding for pre-10.11 using gettimeofday().

It appears this is a common code issue:
https://stackoverflow.com/questions/5167269/clock-gettime-alternative-in-mac-os-x

I can imagine someone trying to write an MQTT based client of OSX which specifically needs the 1.3 features. (websockets anyone ?).   10.12 was released 2 years ago. 

http://gs.statcounter.com/macos-version-market-share/desktop/worldwide

seems to indicate roughly 14.16 + 8.83 + 3.04 + 1.39 = 27.4 %. of OS X users would have problems.

**Comment by icraggs** [comment]
It's easy to revert to using gettimeofday(), and never had complaints about support for older versions of OS/X then, so I think I'll just do that.  The change has no effect on functionality, in the absence of CLOCK_MONOTONIC working.
